CIFAR_PATH = "cifar-10-batches-py/"
H = W = 32
C = 3
CIFAR_IMAGE_SIZE = H * W * C
CIFAR_CLASS_COUNT = 10

HIDDEN_WIDTH_FCN = 256
HIDDEN_WIDTHS_CCN = [64, 16]
DEPTH_FCN = 1
DROPOUT_FCN = 0
DROPOUT_CNN = 0
